---

- name: Run show commands on routers
  hosts: cisco-routers
  gather_facts: false

  tasks:

    - name: run show commands
      ios_command:
        commands:
          - show arp
          - show ip int br
      register: result

    - name: Debug arp
      debug: var=result.stdout_lines[0]

    - name: Debug sh_ip_int_br
      debug: var=result.stdout_lines[1]
