---

- name: Run cfg commands on router
  hosts: 192.168.100.1
  gather_facts: false

  tasks:

    - name: Remove ACL from interface Fa0/1
      ios_config:
        parents:
          - no ip access-list extended INET-to-LAN
          - int fa0/1
        lines:
          - no ip access-group INET-to-LAN in

#    - name: Remove ACL from config
#         ios_config:
#           lines:
#             - no ip access-list extended INET-to-LAN

    - name: Config ACL
      ios_config:
        parents:
          - ip access-list extended INET-to-LAN
        lines:
          - permit tcp 10.0.1.0 0.0.0.255 any eq www
          - permit tcp 10.0.1.0 0.0.0.255 any eq 22
          - permit tcp 10.0.1.0 0.0.0.255 any eq telnet
          - permit icmp any any
      register: cfg


    - name: Apply ACL on interface Fa0/1
      ios_config:
        parents:
          - int fa0/1
        lines:
          - ip access-group INET-to-LAN in

    - name: Show config updates
      debug: var=cfg.updates
      when: cfg.changed
