---

- name: Run show commands on routers
  hosts: cisco-routers
  gather_facts: false

  tasks:

    - name: run show commands
      ios_command:
        commands:
          - show arp
          - show ip int br
      register: result

    - name: Debug registered var
      debug: var=result.stdout_lines

